### ISSUE TITLE
Does not consider all images, only few are selected

### ISSUE THREAD

**Issue by akshayjrkp** [Jumabek/convert_caltech_annos_to_yolo#1]
Hi, thanks for the script.

I have 4250 images from the training dataset with their corresponding annotation files. I used Matlab toolkit to extract the .jpg and .txt files.
When I run the script it outputs the annotations for few files only. I changed the variable "skip" to "1", still annotations for only 1592 images are generated.
How to generate the annotations for every image?
Please help. Thanks a lot in advance.

Akshay

**Comment by Jumabek** [comment]
Hi @akshayjrkp , just delete the filter condition here 
https://github.com/Jumabek/convert_caltech_annos_to_yolo/blob/master/convert_caltech_annos_to_yolo.py#L93

**Comment by akshayjrkp** [comment]
Thank you for the solution.
